name: arpit_s_application4
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  flutter_staggered_grid_view: ^0.4.1
  smooth_page_indicator: ^1.0.0+2
  dotted_border: 2.0.0+1
  flutter_screenutil: ^5.6.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
